kind: pipeline
name: default

steps:

  - name: build
    image: golang:alpine
    environment:
      CGO_ENABLED: 0
      GOPROXY: https://proxy.golang.org
    commands:
      - apk --no-cache add syslog-ng bash
      - syslogd
      - ln -sf /var/run/log /var/run/syslog

      - go test -mod=vendor .
      - GOARCH=386   go build -mod=vendor -o cronguard-linux-386 .
      - GOARCH=amd64 go build -mod=vendor -o cronguard-linux-amd64 .
      - GOARCH=arm   go build -mod=vendor -o cronguard-linux-arm .
      - GOARCH=arm64 go build -mod=vendor -o cronguard-linux-arm64 .

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - cronguard-linux-386
        - cronguard-linux-amd64
        - cronguard-linux-arm
        - cronguard-linux-arm64
      checksum:
        - md5
        - sha1
        - sha256
    when:
      event: tag
